#------------------------------------------------------------------------------
# Makefile
#
# For building dynamic-surface-water-extent.
#------------------------------------------------------------------------------
.PHONY: all install clean

# Inherit from upper-level make.config
TOP = ../..
include $(TOP)/make.config

bin_install_path = $(dswe_algorithm_dir)/bin

# Set up compile options
CC = gcc
RM = rm -f
EXTRA_OPTIONS = $(static_option) $(threading_options) $(profiling_options)
EXTRA = -Wall -g -O2 $(EXTRA_OPTIONS)

# Define the include files
INC = build_slope_band.h  const.h  get_args.h  input.h  output.h  utilities.h
INCDIR  = -I. -I$(XML2INC) -I$(ESPAINC)
NCFLAGS = $(EXTRA) $(INCDIR)

# Define the source code and object files
SRC = \
      utilities.c         \
      get_args.c          \
      input.c             \
      output.c            \
      build_slope_band.c  \
      dswe.c
OBJ = $(SRC:.c=.o)

# Define the object libraries
EXLIB = -L$(ESPALIB) -l_espa_raw_binary -l_espa_common \
        -l_espa_format_conversion \
        -L$(XML2LIB) -lxml2 \
        -L$(LZMALIB) -llzma \
        -L$(ZLIBLIB) -lz
MATHLIB = -lm
LOADLIB = $(EXLIB) $(MATHLIB)

# Define the executable
EXE = dswe

# Target for the executable
all: $(EXE)

$(EXE): $(OBJ) $(INC)
	$(CC) $(EXTRA) -o $(EXE) $(OBJ) $(LOADLIB)

install:
	install -d $(link_path)
	install -d $(bin_install_path)
	install -m 755 $(EXE) $(bin_install_path)
	ln -sf ../$(project_name)/$(dswe_algorithm)/bin/$(EXE) $(link_path)/$(EXE)


clean:
	$(RM) *.o $(EXE)

$(OBJ): $(INC)

.c.o:
	$(CC) $(NCFLAGS) -c $<

