#------------------------------------------------------------------------------
# Makefile
#
# Simple makefile for installing the scripts.
#------------------------------------------------------------------------------

# Target for the executable
all:

install:
	cp ../scripts/create_dem.py $(BIN)
	cp ../scripts/do_surface_water_extent.py $(BIN)

